import { Stamp } from "./types";

export const MOCK_STAMPS: Stamp[] = [
  {
    id: "mock-1",
    creator_name: "DanBuilds",
    creator_wallet: "0x1234...abcd",
    subject_type: "human",
    stamp_type: "content",
    description: "Generated 25,400 impressions from a Base ecosystem thread",
    source_link: "https://x.com",
    metrics_views: 25400,
    metrics_clicks: 1200,
    verification_level: "verified",
    reward_token: "USDC",
    reward_amount: 50,
    score: 87,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-2",
    creator_name: "AstraAgent",
    subject_type: "agent",
    agent_platform: "Virtuals",
    stamp_type: "trade",
    description: "Completed 14 trade actions with 81% success rate",
    metrics_volume: 42000,
    verification_level: "self",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-3",
    creator_name: "BuilderAlex",
    creator_wallet: "0x5678...efgh",
    subject_type: "human",
    stamp_type: "partnership",
    description: "Closed 1 partnership campaign for a Base protocol, bringing 400 new users",
    source_link: "https://github.com",
    metrics_leads: 400,
    verification_level: "verified",
    reward_token: "USDC",
    reward_amount: 100,
    score: 92,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-4",
    creator_name: "ScoutAgent",
    subject_type: "agent",
    agent_platform: "Custom",
    stamp_type: "growth",
    description: "Generated 18 qualified leads for a Base-native protocol in 48 hours",
    metrics_leads: 18,
    verification_level: "self",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-5",
    creator_name: "CryptoKai",
    creator_wallet: "0x9abc...1234",
    subject_type: "human",
    stamp_type: "build",
    description: "Shipped v2 of open-source onchain analytics dashboard with 3 new integrations",
    source_link: "https://github.com",
    metrics_views: 8900,
    verification_level: "self",
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-6",
    creator_name: "TradePilot",
    subject_type: "agent",
    agent_platform: "Virtuals",
    stamp_type: "trade",
    description: "Executed 11 DeFi strategies with positive net outcome on Base",
    metrics_volume: 89000,
    verification_level: "verified",
    reward_amount: 25,
    reward_token: "USDC",
    score: 79,
    created_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
];
