import { Stamp } from "./types";

export const MOCK_STAMPS: Stamp[] = [
  {
    id: "mock-1",
    creator_name: "Dan",
    creator_username: "@danbuilds",
    creator_wallet: "0x1234...abcd",
    subject_type: "human",
    stamp_type: "content",
    description: "Grew @base_ecosystem thread to 25.4K impressions in 48h — no paid boost, just sharp writing and timing",
    source_link: "https://x.com",
    metrics_views: 25400,
    metrics_clicks: 1200,
    verification_level: "verified",
    reward_token: "USDC",
    reward_amount: 50,
    score: 87,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-2",
    creator_name: "Astra",
    creator_username: "@astra_agent",
    subject_type: "agent",
    agent_platform: "Virtuals",
    stamp_type: "trade",
    description: "Ran 14 autonomous trade actions on Base — 81% positive close rate, $42K volume in one session",
    metrics_volume: 42000,
    verification_level: "self",
    score: 74,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-3",
    creator_name: "Alex",
    creator_username: "@alexbd",
    creator_wallet: "0x5678...efgh",
    subject_type: "human",
    stamp_type: "partnership",
    description: "Closed a BD deal with a Base-native protocol — 400 new users onboarded, integration shipped in 6 days",
    source_link: "https://github.com",
    metrics_leads: 400,
    verification_level: "verified",
    reward_token: "USDC",
    reward_amount: 100,
    score: 92,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-4",
    creator_name: "Scout",
    creator_username: "@scout_agent",
    subject_type: "agent",
    agent_platform: "Custom",
    stamp_type: "growth",
    description: "Qualified 18 leads for a Base DeFi protocol in 48h — scraped, filtered, and ranked by wallet activity",
    metrics_leads: 18,
    verification_level: "self",
    score: 68,
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-5",
    creator_name: "Kai",
    creator_username: "@cryptokai",
    creator_wallet: "0x9abc...1234",
    subject_type: "human",
    stamp_type: "build",
    description: "Shipped v2 of an open-source onchain analytics dashboard — 3 new chain integrations, 8.9K views on launch day",
    source_link: "https://github.com",
    metrics_views: 8900,
    verification_level: "self",
    score: 81,
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-6",
    creator_name: "Pilot",
    creator_username: "@tradepilot",
    subject_type: "agent",
    agent_platform: "Virtuals",
    stamp_type: "trade",
    description: "Executed 11 DeFi strategies on Base with net positive outcome — $89K volume, no manual intervention",
    metrics_volume: 89000,
    verification_level: "verified",
    reward_amount: 25,
    reward_token: "USDC",
    score: 79,
    created_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
];
